### PR TITLE
Add tabs to doc :art:

### LINKED ISSUE #10: Табы с разными вариантами получения исходников
https://docs.the-tale.org/ru/stable/development/install.html#id2
Предлагаю создать табы `Clone with HTTPS` и `Clone with SSH` здесь:
```
git clone https://github.com/Tiendil/the-tale.git
git clone https://github.com/Tiendil/deworld.git
git clone https://github.com/Tiendil/dext.git
git clone https://github.com/Tiendil/questgen.git
```

### PR DESCRIPTION
**Pull request by serhii73**
Resolve #10

### CODE REVIEW

**Comment by serhii73** [comment]
Screenshot from 2019-07-10 20-52-29

**Comment by serhii73** [comment]
@Tiendil What do you think about this PR?

**Comment by serhii73** [comment]
@Tiendil поменять мастер на девелоп?

**Comment by Tiendil** [comment]
Спасибо

**Pull request merged**
